(()=>{'use strict';
const COLORS=['red','blue','green','yellow'];
const COLOR_NAMES={red:'Czerwony',blue:'Niebieski',green:'Zielony',yellow:'Żółty'};
const COLOR_CSS={red:'#d92731',blue:'#1171bd',green:'#17933c',yellow:'#f1b90f'};
const ART={
  '0':{key:'duckman',name:'Officer Duckman',icon:'★'},'1':{key:'harlow',name:'Dr. Harlow',icon:'✚'},'2':{key:'barney',name:'Barney',icon:'●'},'3':{key:'ratthew',name:'Ratthew',icon:'★'},'4':{key:'ron',name:'Ron from Accounting',icon:'▦'},'5':{key:'liz',name:'Liz',icon:'♥'},'6':{key:'sam',name:'Sam',icon:'●'},'7':{key:'blackEyes',name:'Black Eyes',icon:'◉'},'8':{key:'hollow',name:'Hollow Face',icon:'●'},'9':{key:'mismatchFace',name:'Mismatching Face',icon:'✚'},draw2:{key:'shopNurse',name:'Shopkeeper Nurse',icon:'+2'},skip:{key:'smile',name:'Smiling with Creepy Eyes',icon:'⊘'},reverse:{key:'threeEyes',name:'Three Eyes',icon:'↔'},wild:{key:'ghostWild',name:'Ghost',icon:'✦'},wild4:{key:'stalker',name:'Stalker',icon:'✦'}
};
const PLAYERS=[{id:'you',name:'Intern',art:'harlow',human:true},{id:'barney',name:'Barney',art:'barney'},{id:'ratthew',name:'Ratthew',art:'ratthew'},{id:'ron',name:'Ron from Accounting',art:'ron'}];
const BARKS={barney:['Dobra karta.','Heh.','Jeszcze jedna.'],ratthew:['Pssst.','To działa.','Zmiana kierunku?'],ron:['Zgodnie z raportem.','W księgach się zgadza.','Przyjęte.']};
const S={deck:[],discard:[],hands:[[],[],[],[]],current:0,direction:1,color:null,busy:false,drawnCard:null,awaitingPass:false,unoDeclared:false,winner:null,pendingWild:null,pendingDraw:0,pendingDrawType:null,started:false,logs:[]};
const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)];let uid=0;
function makeCard(color,value){return{id:`c${++uid}`,color,value,type:typeof value==='number'||/^\d$/.test(String(value))?'number':value}}
function makeDeck(){const d=[];for(const color of COLORS){d.push(makeCard(color,'0'));for(let n=1;n<=9;n++)for(let copy=0;copy<2;copy++)d.push(makeCard(color,String(n)));for(const v of ['skip','reverse','draw2'])for(let copy=0;copy<2;copy++)d.push(makeCard(color,v))}for(let i=0;i<4;i++){d.push(makeCard('wild','wild'));d.push(makeCard('wild','wild4'))}return shuffle(d)}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function nextSeat(from=S.current){return(from+S.direction+4)%4}function top(){return S.discard[S.discard.length-1]}
function refill(){if(S.deck.length)return;const keep=S.discard.pop();S.deck=shuffle(S.discard.splice(0));S.discard=[keep];log('Przetasowano stos odrzuconych.')}
function drawOne(seat){refill();const c=S.deck.pop();if(c)S.hands[seat].push(c);return c}
function canPlay(c,seat=S.current){const t=top();if(!t)return true;if(S.pendingDraw>0)return c.value==='draw2';if(c.value==='wild')return true;if(c.value==='wild4')return !S.hands[seat].some(x=>x.id!==c.id&&x.color===S.color);if(c.color===S.color)return true;if(c.type==='number'&&t.type==='number'&&c.value===t.value)return true;if(c.type!=='number'&&c.type===t.type)return true;return false}
function faceMeta(c){return ART[c.value]||ART['0']}function corner(c){if(c.type==='number')return c.value;if(c.value==='skip')return'⊘';if(c.value==='reverse')return'↔';if(c.value==='draw2')return'+2';if(c.value==='wild4')return'+4';return'W'}
function cardEl(c,{interactive=false}={}){const m=faceMeta(c),el=document.createElement('div');el.className='card';el.dataset.id=c.id;const bg=c.color==='wild'?'wild':c.color;el.innerHTML=`<div class="card-bg ${bg}"></div><div class="pattern"></div><div class="corner tl">${corner(c)}</div><div class="corner br">${corner(c)}</div>${c.value==='skip'?'<div class="action-title">SKIP</div>':''}${c.value==='reverse'?'<div class="action-title">REVERSE</div>':''}${c.value==='draw2'?'<div class="action-title">DRAW 2</div>':''}${c.value==='wild4'?'<div class="action-title">WILD +4</div>':''}${c.value==='wild'?'<div class="action-title">WILD</div>':''}<div class="badge">${m.icon}</div><div class="portrait-frame"><div class="portrait p-${m.key}"></div></div><div class="nameplate">${m.name}</div><div class="brandmark">ANIMAL<br>HOSPITAL</div>${c.color==='wild'?'<div class="wild-wheel"></div>':''}`;if(interactive){const legal=canPlay(c,0)&&S.current===0&&!S.busy&&!S.winner&&(!S.awaitingPass||c.id===S.drawnCard);el.classList.add(legal?'playable':'blocked');el.tabIndex=legal?0:-1;el.onclick=()=>humanPlay(c.id);el.onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&legal){e.preventDefault();humanPlay(c.id)}}}return el}
function seatPortrait(key){return`<div class="seat-avatar"><div class="portrait p-${key}"></div></div>`}
function renderSeats(){[1,2,3].forEach(i=>{const p=PLAYERS[i],root=$(`.seat[data-seat="${i}"]`);root.innerHTML=`${seatPortrait(p.art)}<strong>${p.name}</strong><small>Night-shift bot</small><div class="count">${S.hands[i].length} kart${S.hands[i].length===1?' · UNO!':''}</div>`;root.classList.toggle('active',S.current===i&&!S.winner);const mini=$(`[data-mini="${i}"]`);mini.innerHTML='';for(let n=0;n<Math.min(S.hands[i].length,14);n++){const x=document.createElement('span');x.className='mini-card';mini.appendChild(x)}})}
function renderHand(){const h=$('#hand');h.innerHTML='';const cards=S.hands[0],total=cards.length;cards.forEach((c,i)=>{const el=cardEl(c,{interactive:true}),angle=(i-(total-1)/2)*2.8,lift=Math.abs(i-(total-1)/2)*1.2;el.style.transform=`rotate(${angle}deg) translateY(${lift}px)`;if(c.id===S.drawnCard)el.style.boxShadow='0 0 0 3px rgba(244,192,93,.9),0 15px 25px rgba(0,0,0,.32)';h.appendChild(el)});$('#humanCount').textContent=cards.length}
function renderDiscard(){const d=$('#discard');d.innerHTML='';if(top())d.appendChild(cardEl(top()))}
function render(){renderHand();renderSeats();renderDiscard();$('#deckStat').textContent=S.deck.length;$('#dirStat').textContent=S.direction===1?'↻':'↺';$('#colorStat').textContent=S.color?COLOR_NAMES[S.color]:'—';$('#departmentName').textContent=S.color?COLOR_NAMES[S.color]:'—';$('#colorOrb').style.background=S.color?COLOR_CSS[S.color]:'#777';const humanTurn=S.started&&!S.winner&&S.current===0&&!S.busy;$('#turnStat').textContent=!S.started?'Ready':S.winner?'Koniec':humanTurn?'Twój ruch':PLAYERS[S.current].name;$('#notice').textContent=!S.started?'Rozpocznij nocny dyżur':S.winner?`${PLAYERS[S.winner].name} wygrywa`:humanTurn?(S.awaitingPass?'Zagraj dobraną kartę albo spasuj':'Twój ruch'): `${PLAYERS[S.current].name} analizuje ruch`;$('#drawBtn').disabled=!humanTurn||S.awaitingPass;$('#passBtn').disabled=!humanTurn||!S.awaitingPass;$('#unoBtn').disabled=!(humanTurn&&S.hands[0].length===2&&!S.unoDeclared);$('#humanPill').classList.toggle('active',humanTurn);$('#hint').textContent=S.awaitingPass?'Tylko dobraną kartę możesz teraz zagrać.':S.pendingDraw>0?`Ciąg dobierania: +${S.pendingDraw}. Zagraj +2 albo dobierz.`:`Na wierzchu: ${cardName(top())}`;renderLog()}
function log(t){S.logs.push(t);renderLog()}function renderLog(){const root=$('#log');root.innerHTML='';S.logs.slice(-22).reverse().forEach(t=>{const d=document.createElement('div');d.className='log-line';d.textContent=t;root.appendChild(d)})}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1600)}
function cardName(c){if(!c)return'—';const m=faceMeta(c);if(c.type==='number')return`${COLOR_NAMES[c.color]} ${c.value} · ${m.name}`;if(c.value==='skip')return`${COLOR_NAMES[c.color]} Skip · ${m.name}`;if(c.value==='reverse')return`${COLOR_NAMES[c.color]} Reverse · ${m.name}`;if(c.value==='draw2')return`${COLOR_NAMES[c.color]} Draw Two · ${m.name}`;if(c.value==='wild4')return'Wild +4 · Stalker';return'Wild · Ghost'}
function bubble(seat,text){if(seat===0)return;const p=PLAYERS[seat],old=document.querySelector(`.bubble[data-b="${p.id}"]`);if(old)old.remove();const b=document.createElement('div');b.dataset.b=p.id;b.className=`bubble ${seat===2?'top':seat===1?'left':'right'}`;b.textContent=text;$('#table').appendChild(b);setTimeout(()=>b.remove(),1600)}
function newGame(){uid=0;Object.assign(S,{deck:makeDeck(),discard:[],hands:[[],[],[],[]],current:0,direction:1,color:null,busy:false,drawnCard:null,awaitingPass:false,unoDeclared:false,winner:null,pendingWild:null,pendingDraw:0,pendingDrawType:null,started:true,logs:[]});for(let r=0;r<7;r++)for(let p=0;p<4;p++)drawOne(p);let first;do{first=S.deck.pop();if(first.type!=='number')S.deck.unshift(first)}while(first.type!=='number');S.discard=[first];S.color=first.color;log(`Pierwsza karta: ${cardName(first)}.`);render()}
function removeCard(seat,id){const i=S.hands[seat].findIndex(c=>c.id===id);return i<0?null:S.hands[seat].splice(i,1)[0]}
function humanPlay(id){if(S.current!==0||S.busy||S.winner)return;const c=S.hands[0].find(x=>x.id===id);if(!c)return;if(S.awaitingPass&&id!==S.drawnCard){toast('Po dobraniu możesz zagrać tylko dobraną kartę.');return}if(!canPlay(c,0)){toast(c.value==='wild4'?'Stalker +4 jest teraz nielegalny.':S.pendingDraw>0?'Musisz dołożyć +2 albo dobrać całą karę.':'Ta karta nie pasuje.');return}if(c.color==='wild'){S.pendingWild=id;$('#colorOverlay').classList.add('show');return}playResolved(0,removeCard(0,id),null)}
function chooseColor(color){$('#colorOverlay').classList.remove('show');if(!S.pendingWild)return;const c=removeCard(0,S.pendingWild);S.pendingWild=null;playResolved(0,c,color)}
function playResolved(seat,c,chosen){S.discard.push(c);S.color=c.color==='wild'?(chosen||botColor(seat)):c.color;S.drawnCard=null;S.awaitingPass=false;log(`${PLAYERS[seat].name} zagrywa ${cardName(c)}.`);if(c.value==='skip')bubble(seat,'SKIP!');if(c.value==='reverse')bubble(seat,'REVERSE!');if(c.value==='draw2')bubble(seat,'+2!');if(c.value==='wild')bubble(seat,`Wild: ${COLOR_NAMES[S.color]}`);if(c.value==='wild4')bubble(seat,'STALKER +4!');if(S.hands[seat].length===0){S.winner=seat;render();endGame();return}if(S.hands[seat].length===1){if(seat===0&&!S.unoDeclared){drawOne(0);drawOne(0);log('Brak deklaracji UNO — kara 2 karty.');toast('Brak UNO! +2 karty kary.')}else if(seat!==0){log(`${PLAYERS[seat].name}: UNO!`);bubble(seat,'UNO!')}}S.unoDeclared=false;let next=nextSeat(seat);if(c.value==='reverse'){S.direction*=-1;next=nextSeat(seat)}if(c.value==='skip'){log(`${PLAYERS[next].name} traci turę.`);next=nextSeat(next)}if(c.value==='draw2'){S.pendingDraw+=2;S.pendingDrawType='draw2'}if(c.value==='wild4'){for(let i=0;i<4;i++)drawOne(next);log(`${PLAYERS[next].name} dobiera 4 karty i traci turę.`);next=nextSeat(next)}S.current=next;render();setTimeout(maybeBot,520)}
function humanDraw(){if(S.current!==0||S.busy||S.awaitingPass||S.winner)return;if(S.pendingDraw>0){const penalty=S.pendingDraw;for(let i=0;i<penalty;i++)drawOne(0);log(`Intern dobiera ${penalty} kart i traci turę.`);toast(`Dobierasz ${penalty} kart.`);S.pendingDraw=0;S.pendingDrawType=null;S.unoDeclared=false;S.current=nextSeat(0);render();setTimeout(maybeBot,420);return}const c=drawOne(0);S.drawnCard=c.id;S.awaitingPass=true;log(`Dobierasz: ${cardName(c)}.`);render();toast(canPlay(c,0)?'Możesz zagrać dobraną kartę albo spasować.':'Karta nie pasuje — spasuj.')}
function pass(){if(S.current!==0||!S.awaitingPass)return;S.drawnCard=null;S.awaitingPass=false;S.unoDeclared=false;S.current=nextSeat(0);log('Intern pasuje.');render();setTimeout(maybeBot,420)}
function declareUno(){if(S.current===0&&S.hands[0].length===2){S.unoDeclared=true;toast('UNO!');log('Intern zgłasza UNO.');render()}}
function botColor(seat){const tally={red:0,blue:0,green:0,yellow:0};S.hands[seat].forEach(c=>{if(tally[c.color]!==undefined)tally[c.color]++});return COLORS.slice().sort((a,b)=>tally[b]-tally[a])[0]}
function botScore(c,seat){let s=c.value==='wild4'?90:c.value==='wild'?70:c.value==='draw2'?58:c.value==='skip'?45:c.value==='reverse'?38:Number(c.value)||0;if(c.color===S.color)s+=18;if(S.pendingDraw>0&&c.value==='draw2')s+=120;s+=S.hands[seat].filter(x=>x.color===c.color).length*3;return s+Math.random()}
function maybeBot(){if(S.winner||S.current===0)return;const seat=S.current;S.busy=true;render();setTimeout(()=>{let legal=S.hands[seat].filter(c=>canPlay(c,seat));if(S.pendingDraw>0&&!legal.length){const penalty=S.pendingDraw;for(let i=0;i<penalty;i++)drawOne(seat);log(`${PLAYERS[seat].name} dobiera ${penalty} kart i traci turę.`);bubble(seat,`+${penalty}`);S.pendingDraw=0;S.pendingDrawType=null;S.busy=false;S.current=nextSeat(seat);render();setTimeout(maybeBot,420);return}if(!legal.length){const d=drawOne(seat);log(`${PLAYERS[seat].name} dobiera kartę.`);if(canPlay(d,seat))legal=[d]}if(legal.length){legal.sort((a,b)=>botScore(b,seat)-botScore(a,seat));const c=legal[0],color=c.color==='wild'?botColor(seat):null;S.busy=false;playResolved(seat,removeCard(seat,c.id),color);bubble(seat,BARKS[PLAYERS[seat].id][Math.floor(Math.random()*BARKS[PLAYERS[seat].id].length)])}else{S.busy=false;S.current=nextSeat(seat);render();setTimeout(maybeBot,420)}},650+Math.random()*450)}
function endGame(){const you=S.winner===0;$('#endTitle').textContent=you?'Dyżur wygrany!':`${PLAYERS[S.winner].name} wygrywa`;$('#endText').textContent=you?'Pozbyłeś się wszystkich kart. Animal Hospital zamyka nocną zmianę.':`${PLAYERS[S.winner].name} jako pierwszy pozbywa się całej ręki.`;setTimeout(()=>$('#endOverlay').classList.add('show'),450)}
$('#startBtn').onclick=()=>{$('#startOverlay').classList.remove('show');newGame()};$('#againBtn').onclick=()=>{$('#endOverlay').classList.remove('show');newGame()};$('#restartBtn').onclick=newGame;$('#drawBtn').onclick=humanDraw;$('#deck').onclick=humanDraw;$('#passBtn').onclick=pass;$('#unoBtn').onclick=declareUno;$$('.color-btn').forEach(b=>b.onclick=()=>chooseColor(b.dataset.color));function showRules(){$('#rulesOverlay').classList.add('show')}function hideRules(){$('#rulesOverlay').classList.remove('show')}$('#rulesBtn').onclick=showRules;$('#menuRulesBtn').onclick=showRules;$('#closeRulesBtn').onclick=hideRules;
window.AnimalUNO={state:S,newGame,canPlay,makeDeck,debug:{ART,PLAYERS,COLORS,deckSize:()=>makeDeck().length}};render();
})();
